gui:
  env:
    GOROOT: '$RUNE_DATADIR/pkg/$RUNE_PKG_ID/$RUNE_PKG_VERSION'
extensions:
  go:
    path: '$RUNE_DATADIR/bin/extension_go'
lsp:
  icons:
    inline: "󰁔"
    escape: "󰁝"
    bounds: "󰅪"
    nilcheck: "∅"
    compiler: "⚙"
editor:
  icons:
    .go: 󰟓
