gui:
  env:
    GOROOT: '$RUNE_DATADIR/pkg/$RUNE_PKG_ID/$RUNE_PKG_VERSION'
extensions:
  go:
    path: '$RUNE_DATADIR/bin/extension_go'
    config:
      lsp_path: ""
      addr: localhost:6060
      logfile: /Users/ernestrc/.rune/logs/lsp/gopls.log
      # rpc_trace: true
      # trace: verbose
debugger:
  go:
    command: "dlv dap --listen={addr}"
    adapter_id: "dlv-dap"
    launch:
      mode: "debug"
      outputMode: "remote"
    attach:
      mode: "local"
lsp:
  icons:
    inline: "󰁔"
    escape: "󰁝"
    bounds: "󰅪"
    nilcheck: "∅"
    compiler: "⚙"
editor:
  icons:
    .go: 󰟓
  comments:
    go:
      line:
        - "//"
      block:
        - "/*"
        - "*/"
